// <auto-generated />
namespace SipraişUygulaması.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201912240741322_sv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
